name: Test Syntax
on:
  repository_dispatch:
    types:
      - new_release
  push:
    branches    : ["main"]
    paths-ignore:
      - '.github/workflows/**/*'
      - 'doc/**'
      - '**.md'
      - '**.sublime-*'
  pull_request  :
    branches    : ["**"]
    paths-ignore:
      - '.github/workflows/**/*'
      - 'doc/**'
      - '**.md'
      - '**.sublime-*'
  workflow_dispatch:
jobs:
  unittesting:
    name: Unittesting (${{ matrix.os }})
    strategy   :
      fail-fast: false
      matrix   :
        st-v   : [4]
        os     : ["ubuntu-latest"]
    runs-on    : ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2 26-01 c04
        with:
          persist-credentials: false

      - name: Setup UnitTesting
        uses: SublimeText/UnitTesting/actions/setup@924d620a7e0ef373f47b30a728af931e0887dfee #branch v1 26-02 c04
        with:
          package-name        : 'KDL'
          sublime-text-version:  ${{ matrix.st-v }}

      - name: Run UnitTesting
        uses: SublimeText/UnitTesting/actions/run-syntax-tests@924d620a7e0ef373f47b30a728af931e0887dfee #branch v1 26-02 c04
        with:
          compatibility       : false # syntax uses (negative) look behinds/atomic groups/back refs, which are not compatible with the latest ST syntax
